# URLs
EXTERNAL_FILES_DIR = "https://github.com/jpmilcent/npo-api/releases/download/v0.0.1-alpha"

# Filenames
IMAGE_01_JPG = "image_01.jpg"
IMAGE_02_JPG = "image_02.jpg"
IMAGE_03_DNG = "image_03.dng"
IMAGE_04_DNG = "image_04.dng"
IMAGE_05_NEF = "image_05.nef"
IMAGE_06_NEF = "image_06.nef"

# Map filenames to download URLs
EXTERNAL_FILES = {
    IMAGE_01_JPG: f"{EXTERNAL_FILES_DIR}/{IMAGE_01_JPG}",
    IMAGE_02_JPG: f"{EXTERNAL_FILES_DIR}/{IMAGE_02_JPG}",
    IMAGE_03_DNG: f"{EXTERNAL_FILES_DIR}/{IMAGE_03_DNG}",
    IMAGE_04_DNG: f"{EXTERNAL_FILES_DIR}/{IMAGE_04_DNG}",
    IMAGE_05_NEF: f"{EXTERNAL_FILES_DIR}/{IMAGE_05_NEF}",
    IMAGE_06_NEF: f"{EXTERNAL_FILES_DIR}/{IMAGE_06_NEF}",
}

# Domain constants
PERCEPTUAL_HASH_LENGTH = 16

# Error Codes
ERROR_DUPLICATE_PERCEPTUAL_HASH = "DUPLICATE_PERCEPTUAL_HASH"
ERROR_FILE_NOT_FOUND = "FILE_NOT_FOUND"
ERROR_RAW_METADATA_NOT_FOUND = "RAW_METADATA_NOT_FOUND"
ERROR_PHOTOGRAPHY_METADATA_NOT_FOUND = "PHOTOGRAPHY_METADATA_NOT_FOUND"
ERROR_METADATA_WEBSERVICE_NOT_FOUND = "METADATA_WEBSERVICE_NOT_FOUND"
ERROR_SETTINGS_VERSION_NOT_FOUND = "SETTINGS_VERSION_NOT_FOUND"
