# URLs
EXTERNAL_FILES_DIR = "https://github.com/jpmilcent/npo-api/releases/download/v0.1.0-alpha"

# Filenames
IMAGE_01_JPG = "image_01.jpg"
IMAGE_02_JPG = "image_02.jpg"
IMAGE_03_DNG = "image_03.dng"
IMAGE_04_DNG = "image_04.dng"
IMAGE_05_NEF = "image_05.nef"
IMAGE_06_NEF = "image_06.nef"

# Map filenames to download URLs
EXTERNAL_FILES = {
    IMAGE_01_JPG: f"{EXTERNAL_FILES_DIR}/{IMAGE_01_JPG}",
    IMAGE_02_JPG: f"{EXTERNAL_FILES_DIR}/{IMAGE_02_JPG}",
    IMAGE_03_DNG: f"{EXTERNAL_FILES_DIR}/{IMAGE_03_DNG}",
    IMAGE_04_DNG: f"{EXTERNAL_FILES_DIR}/{IMAGE_04_DNG}",
    IMAGE_05_NEF: f"{EXTERNAL_FILES_DIR}/{IMAGE_05_NEF}",
    IMAGE_06_NEF: f"{EXTERNAL_FILES_DIR}/{IMAGE_06_NEF}",
}

# Domain constants
PERCEPTUAL_HASH_LENGTH = 16

# Error Codes
ERROR_DUPLICATE_PERCEPTUAL_HASH = "DUPLICATE_PERCEPTUAL_HASH"
ERROR_IMAGE_NOT_FOUND = "IMAGE_NOT_FOUND"
ERROR_IMAGES_WEBSERVICE_NOT_FOUND = "IMAGES_WEBSERVICE_NOT_FOUND"
ERROR_RAW_METADATA_NOT_FOUND = "RAW_METADATA_NOT_FOUND"
ERROR_PHOTOGRAPHY_METADATA_NOT_FOUND = "PHOTOGRAPHY_METADATA_NOT_FOUND"
ERROR_SETTINGS_WEBSERVICE_NOT_FOUND = "SETTINGS_WEBSERVICE_NOT_FOUND"
ERROR_SETTINGS_VERSION_NOT_FOUND = "SETTINGS_VERSION_NOT_FOUND"
ERROR_IMAGE_DZI_NOT_FOUND = "IMAGE_DZI_NOT_FOUND"
ERROR_FILE_TOO_LARGE = "FILE_TOO_LARGE"
ERROR_INSUFFICIENT_STORAGE = "INSUFFICIENT_STORAGE"
ERROR_IMAGE_DECODING_ERROR = "IMAGE_DECODING_ERROR"
ERROR_NOT_VERIFIED_EMAIL_AUTH_ERROR = "NOT_VERIFIED_EMAIL_AUTH_ERROR"
ERROR_NO_USER_INFO_AUTH_ERROR = "NO_USER_INFO_AUTH_ERROR"
ERROR_HEALTH_WEBSERVICE_NOT_FOUND = "HEALTH_WEBSERVICE_NOT_FOUND"
ERROR_AUTH_PROVIDER_NOT_FOUND = "AUTH_PROVIDER_NOT_FOUND"
ERROR_NO_EMAIL_AUTH_ERROR = "NO_EMAIL_AUTH_ERROR"
