from typing import Any

class Error(Exception): ...

class Image:
    width: int
    height: int

    @staticmethod
    def new_from_file(filename: str, **kwargs: Any) -> Image: ...
    @staticmethod
    def new_from_buffer(data: bytes | str, options: str, **kwargs: Any) -> Image: ...
    def colourspace(self, space: str, **kwargs: Any) -> Image: ...
    def crop(self, left: int, top: int, width: int, height: int, **kwargs: Any) -> Image: ...
    def write_to_memory(self) -> bytes: ...
    def thumbnail_image(self, width: int, **kwargs: Any) -> Image: ...
    def autorot(self, **kwargs: Any) -> Image: ...
    def dzsave(self, filename: str, **kwargs: Any) -> None: ...
