from typing import Any

def _(msgid: str, **kwargs: Any) -> str: ...

class BabelConfigs:
    def __init__(self, **kwargs: Any) -> None: ...

class BabelMiddleware:
    def __init__(self, app: Any, **kwargs: Any) -> None: ...
    async def __call__(self, scope: Any, receive: Any, send: Any) -> None: ...
